[theme]
# primary color for interactive elements
primaryColor = "#d33682"
# background color for the main content area
backgroundColor = "#002b36"
# background color for the sidebar and most interactive widgets
secondaryBackgroundColor = "#586e75"
# color used for most of the text
textColor = "#fafafa"
# Font family used for all text in the app, except code blocks
font = "sans serif"
